# Web
server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://127.0.0.1:5432/postgres
    username: postgres
    password: postgres


# MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/com/exsample/jsondemo/jsondemo/repository/mapper/*.xml

#logging:
#  level:
#    org:
#      springframework: WARN
#    com:
#      okome:
#        api:
#          repository:
#            CustomerMapper: DEBUG
